<header>
  <nav id="navbar">
    <div id="top-bar" class="bg-black">
      <div class="container px-2">
        <address>
          <a href="mailto:abidmahmoud8@gmail.com" class="text-white">
            <i class="px-1 far fa-envelope"></i>
            <span class="d-md-none">abidmahmoud8@gmail.com</span>
          </a>
          <br>
          <a href="tel:+21644251581" class="text-white px-2">
            <i class="px-1 fa fa-phone"></i>
            <span class="d-md-none">(216) 44251581</span>
          </a>
        </address>
        <?php if(!$connected):?>
        <a href="?page=connexion" title="connexion" class="text-white">
          <i class="px-1 far fa-user"></i><span class="d-md-none">Connexion</span>
        </a>
        <?php else: ?>
        <div class="dropdown">
          <span class="avatar-container">
            <span class="px-2">Mahmoud</span>
          </span> 
          <div class="dropdown-content">
            <ul>
              <li class="p-2"><a href="/?page=admin">Tableau de board</a></li>
              <li class="p-2"><a href="/?page=profile">Mon profil</a></li>
              <li class="p-2"><a href="/?page=connexion&param=deconnect">Déconnexion</a></li>
            </ul>
          </div>
        </div>
        <?php endif; ?>
      </div>
    </div>
    <div id="menu-bar">
      <div class="container py-3 px-2">
        <a class="current" href="/" title="accueil"><img src="../../public/images/logo.png" alt="logo"></a>
        <ul>
          <li><a href="/" title="accueil" class="text-black">Accueil</a></li>
          <li><a href="?page=products" title="annoces" class="px-2 text-black">Annonces</a></li>
          <li><a href="?page=contact" title="contact" class="text-black">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>