<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Ville</th>
      <th>Etat</th>
      <th>Pay</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($cities as $city) : ?>
    <tr>
      <td><?= $city['id_city']; ?></td>
      <td><?= $city['name']?></td>
      <td><?= $city['state_name']; ?></td>
      <td><?= $city['country_name']; ?></td>
      <td>
        <button 
          data-info='{"db": "cities", "id": "id_city", "value": "<?= $city['id_city']; ?>", "label": "Ville"}' 
          data-modal="city-<?= $city['id_city']; ?>"
          class="btn-danger p-2"
        >
          <i class="fa fa-trash-alt"></i>Supprimer
        </button>
        <button data-modal="city-<?= $city['id_city']; ?>" class="btn-success p-2"><i class="fa fa-pen"></i>Modifier</button>
      </td>
      <div id="<?= 'modal-city-' . $city['id_city']; ?>" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <?php include 'view/components/admin/add-city.phtml'; ?>
        </div>
      </div>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>