<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Ville</th>
      <th>Etat</th>
      <th>Pay</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($cities as $city) : ?>
    <tr>
      <td><?= $city['id_city']; ?></td>
      <td><?= $city['name']?></td>
      <td><?= $city['state_name']; ?></td>
      <td><?= $city['country_name']; ?></td>
      <td>
        <button 
          data-info='{"db": "cities", "id": "id_city", "value": "<?= $city['id_city']; ?>", "label": "Ville"}' 
          data-modal="city-<?= $city['id_city']; ?>"
          class="btn-danger p-2"
        >
          <i class="fa fa-trash-alt"></i>Supprimer
        </button>
        <button class="btn-success p-0"><a class="m-0 p-2" href="/?page=admin&param=city&id_city=<?= $city['id_city']; ?>"><i class="fa fa-pen"></i>Editer</a></button>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>