<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Pay</th>
      <th>ISO Code</th>
      <th>Devise</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($countries as $country) : ?>
    <tr>
      <td><?= $country['id_country']; ?></td>
      <td><?= $country['name']?></td>
      <td><?= $country['iso_code']; ?></td>
      <td><?= $country['currency']; ?></td>
      <td>
        <button 
          data-modal="country-<?= $country['id_country']; ?>" 
          data-info='{"db": "countries", "id": "id_country", "value": "<?= $country['id_country']; ?>", "label": "Pay"}' 
          class="btn-danger p-2"
        >
          <i class="fa fa-trash-alt"></i>Supprimer
        </button>
        <button class="btn-success p-0"><a class="m-0 p-2" href="/?page=admin&param=country&id_country=<?= $country['id_country']; ?>"><i class="fa fa-pen"></i>Editer</a></button>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>