<div id="sidebar">
  <div class="logo-container p-3">
    <a class="current" href="index.php" title="accueil"><img src="../../public/images/logo.png" alt="logo"></a>
  </div>
  <div class="menus-container py-4">
    <ul>
      <li><a class="active" href=""><i class="fa fa-home"></i><span>Dashboard</span></a></li>
      <li><a href=""><i class="fa fa-map-marker-alt"></i><span>Localisations</span></a></li>
      <li><a href=""><i class="fa fa-user"></i><span>Utilisateurs</span></a></li>
      <li><a href=""><i class="fa fa-house-user"></i><span>Annonces</span></a></li>
      <li><a href=""><i class="fa fa-sign-out-alt"></i><span>Déconnexion</span></a></li>
    </ul>
  </div>

</div>