<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Etat</th>
      <th>Pay</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($states as $state) : ?>
    <tr>
      <td><?= $state['id_state']; ?></td>
      <td><?= $state['name']?></td>
      <td><?= $state['country_name']; ?></td>
      <td>
        <button 
          data-modal="state-<?= $state['id_state']; ?>" 
          data-info='{"db": "states", "id": "id_state", "value": "<?= $state['id_state']; ?>", "label": "Etat"}' 
          class="btn-danger p-2"
        ><i class="fa fa-trash-alt"></i>Supprimer</button>
        <button class="btn-success p-0"><a class="m-0 p-2" href="/?page=admin&param=state&id_state=<?= $state['id_state']; ?>"><i class="fa fa-pen"></i>Editer</a></button>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>