<div class="form-container container">
  <div class="input-container">
    <label for="title">Titre</label>
    <input type="text" name="title" placeholder="Titre de votre annonce" class="p-1"/>
    <p id="title-error" class="error"></p>
  </div>
  <button class="btn-primary my-2 float-right" id="add-product-button" onclick="openModal('modal-add-locations')"> Ajouter</button>
  <div id="modal-add-locations" class="modal" >
    <div class="modal-content">
      <p>Ajouter une pay</p>
    </div>
  </div>
</div>