<div class="form-container container connexion-container">
  <h4>Information générale</h4>
  <div class="input-container py-2">
    <label for="title">Titre</label>
    <input type="text" name="title" placeholder="Titre de votre annonce" class="px-1"/>
  </div>
  <div class="input-container py-2">
    <label for="description">Description</label>
    <textarea name="description" rows="5" cols="33" class="px-1" placeholder="Description de votre annonce..."></textarea> 
  </div>
  <input type="file" id="image-uploads" name="image-uploads" accept=".jpg, .jpeg, .png" multiple>
</div>