<div id="admin">
<header class="bg-white">
  <nav id="navbar">
    <div id="menu-bar" class="px-2">
      <i class="fa fa-bars"></i>
      <div class="dropdown">
        <span class="avatar-container">
          <img src="https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png" alt="avatar">
          <span class="px-2">Mahmoud</span>
        </span> 
        <div class="dropdown-content">
          <ul>
            <li class="p-2"><a href="/profile">Mon profil</a></li>
            <li class="p-2"><a href="/deconnect">Déconnexion</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>
<section>
  <h2>HTML Table</h2>
  <table>
    <tr>
      <th>Company</th>
      <th>Contact</th>
      <th>Country</th>
    </tr>
    <tr>
      <td>Alfreds Futterkiste</td>
      <td>Maria Anders</td>
      <td>Germany</td>
    </tr>
    <tr>
      <td>Centro comercial Moctezuma</td>
      <td>Francisco Chang</td>
      <td>Mexico</td>
    </tr>
    <tr>
      <td>Ernst Handel</td>
      <td>Roland Mendel</td>
      <td>Austria</td>
    </tr>
    <tr>
      <td>Island Trading</td>
      <td>Helen Bennett</td>
      <td>UK</td>
    </tr>
    <tr>
      <td>Laughing Bacchus Winecellars</td>
      <td>Yoshi Tannamuri</td>
      <td>Canada</td>
    </tr>
    <tr>
      <td>Magazzini Alimentari Riuniti</td>
      <td>Giovanni Rovelli</td>
      <td>Italy</td>
    </tr>
  </table>
</section>
</div>