<div id="admin">
<header class="bg-white">
  <nav id="navbar">
    <div id="menu-bar" class="px-2">
      <i class="fa fa-bars"></i>
      <div class="dropdown">
        <span class="avatar-container">
          <img src="https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png" alt="avatar">
          <span class="px-2">Mahmoud</span>
        </span> 
        <div class="dropdown-content">
          <ul>
            <li class="p-2"><a href="/profile">Mon profil</a></li>
            <li class="p-2"><a href="/deconnect">Déconnexion</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>
</div>