<h2>Liste des localisations</h2>
<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'countries')" id="opened">Pays</button>
  <button class="tablinks" onclick="openTab(event, 'states')">Etats</button>
  <button class="tablinks" onclick="openTab(event, 'cities')">Villes</button>
</div>
<div id="countries" class="tabcontent">
  <div class="title-container my-2">
    <h4>Liste des Pays</h4>
    <button class="btn-primary my-2 p-0 float-right"><a class="m-0 p-2" href="/?page=admin&param=country">Ajouter</a></button>
  </div>
  <?php include 'view/components/admin/countries.phtml'; ?>
</div>
<div id="states" class="tabcontent">
  <div class="title-container my-2">
    <h4>Liste des Etats</h4>
    <button class="btn-primary my-2 p-0 float-right"><a class="m-0 p-2" href="/?page=admin&param=state">Ajouter</a></button>
  </div>
  <?php include 'view/components/admin/states.phtml'; ?>
</div>
<div id="cities" class="tabcontent">
  <div class="title-container my-2">
    <h4>Liste des Villes</h4>
    <button class="btn-primary my-2 p-0 float-right"><a class="m-0 p-2" href="/?page=admin&param=city">Ajouter</a></button>  </div>
  <?php include 'view/components/admin/cities.phtml'; ?>
</div>