<h2>Liste des utilisateurs</h2>
<table>
  <tr>
    <th>id</th>
    <th>Nom</th>
    <th>E-mail</th>
    <th>N° de téléphone</th>
    <th>Actions</th>
  </tr>
  <?php foreach ($users as $user) : ?>
    <tr>
      <td><?= $user['id_user']; ?></td>
      <td><?= $user['first_name'] . ' ' . $user['last_name']; ?></td>
      <td><?= $user['email']; ?></td>
      <td><?= $user['phone']; ?></td>
      <td>
        <button data-user="<?= $user['id_user']; ?>" class="btn-danger p-2"><i class="fa fa-trash-alt"></i>Supprimer</button>
        <button data-user="<?= $user['id_user']; ?>" class="btn-success p-2"><i class="fa fa-pen"></i>Modifier</button>
      </td>
      <div id="<?= 'modal-' . $user['id_user']; ?>" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <?php include 'view/components/admin/profile.phtml'; ?>
        </div>
      </div>
    </tr>
  <?php endforeach; ?>
</table>