<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Coloc || Appartements partagés à louer</title>
  <link href="../../public/css/products.css" rel="stylesheet">	
  <link href="../../public/css/login.css" rel="stylesheet">	
  <link href="../../public/css/theme.css" rel="stylesheet">	
  <link href="../../public/css/styles.css" rel="stylesheet">	
  <link href="../../public/css/fontawesome-free-5.15.3-web/css/all.min.css" rel="stylesheet">
</head>
<body>
  <?php 
    include 'view/components/showcase/header.phtml';
  ?>
  <main id="profile-layout">
  <?php 
    include 'view/pages/profile/' .$var . '.phtml';
  ?>
  </main>
  <?php 
    include 'view/components/showcase/footer.phtml';

  ?>
    
</body>
</html>