<main>
  <section id="announcements">
    <div class="container">
      <div class="row">
        <div id="sidebar-filter">
          <button id="change-search-btn" type="button">
            <span>
              <h1 class="strong">Pneu 205/55 R16 91V été </h1>
            </span>
            <span>Modifier mon choix</span>
          </button>
          <div id="sidebar-filter-container" class="px-2">
            <h4>Les plus performants</h4>
            <div id="optional-filter" class="form-group">
              <div class="form-check mt-2 pl-0">
                <label class="check form-check-label d-flex" id="runFlatLabel">Pneus anti crevaison</label>
                <input class="form-check-input" type="checkbox" value="is_run_flat">
                <span class="checkmark"></span>
              </div>
              <div class="form-check mt-2 pl-0">
                <label class="check form-check-label d-flex" id="runFlatLabel">Pneus anti crevaison</label>
                <input class="form-check-input" type="checkbox" value="is_run_flat">
                <span class="checkmark"></span>
              </div>
              <div class="form-check mt-2 pl-0">
                <label class="check form-check-label d-flex" id="runFlatLabel">Pneus anti crevaison</label>
                <input class="form-check-input" type="checkbox" value="is_run_flat">
                <span class="checkmark"></span>
              </div>
            </div>
            <hr/>
          </div>
        </div>
        <div id="announcements-container" class="row">
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
          <article class="announcement px-1">
            <div class="announcement-title">
              <h5>Appartement à louer</h5>
            </div>
            <div class="img-container">
              <img src="https://strapid.spid-tech.com/uploads/thumbnail_3286340964913_4_14e92de75b.png" alt="">
            </div>
            <div class="details-container">
              <div class="type-announcement">Appartement à louer</div>
              <p><strong>66€</strong></p>
              <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, dolores?</small></p>
              <a href=""><strong>Voir détails</strong></a>
            </div>
          </article>
        </div>
      </div>
    </div>
    </div>
  </section>
</main>