<footer id="footer">
  <div class="container">
    <ul class="py-4">
      <li>
        <h4>Informations utiles</h4>                    
        <a href="#">Qui sommes-nous?</a>
        <a href="#">Conditions de vente</a>
        <a href="#">Traveltodo vous répond</a>
        <a href="#">Contact</a>
        <a href="#">Points de ventes</a>
      </li>
      <li>
        <h4>Contact</h4>                    
        <a href="#">Qui sommes-nous?</a>
        <a href="#">Conditions de vente</a>
        <a href="#">Traveltodo vous répond</a>
        <a href="#">Contact</a>
        <a href="#">Points de ventes</a>
      </li>
      <li id="possibility3">
        <h4>Contact</h4>                    
        <a href="#">Qui sommes-nous?</a>
        <a href="#">Conditions de vente</a>
        <a href="#">Traveltodo vous répond</a>
        <a href="#">Contact</a>
        <a href="#">Points de ventes</a>
      </li>
      <div class="clear"></div>  
    </ul>
  </div>

</footer>