<header>
  <nav id="navbar">
    <div id="top-bar" class="bg-black">
      <div class="container">
        <address>
          <a href="mailto:abidmahmoud8@gmail.com" class="text-white"><i class="far fa-envelope"></i>abidmahmoud8@gmail.com</a><br>
          <a href="tel:+21644251581" class="text-white px-2"><i class="fa fa-phone"></i>(216) 44251581</a>
        </address>
        <a href="connection.html" title="connexion" class="text-white">
          <i class="far fa-user"></i>Connexion
        </a>
      </div>
    </div>
    <div id="menu-bar">
      <div class="container py-3">
        <a class="current" href="index.php" title="accueil"><img src="../public/images/logo.jfif" alt="logo"></a>
        <ul>
          <li><a href="index.html" title="accueil" class="text-black">Accueil</a></li>
          <li><a href="about.html" title="annoces" class="px-2 text-black">Annoces</a></li>
          <li><a href="contact.html" title="contact" class="text-black">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>