<header>
  <nav id="navbar">
    <div id="top-bar" class="bg-black">
      <div class="container px-2">
        <address>
          <a href="mailto:abidmahmoud8@gmail.com" class="text-white">
            <i class="px-1 far fa-envelope"></i>
            <span class="d-md-none">abidmahmoud8@gmail.com</span>
          </a>
          <br>
          <a href="tel:+21644251581" class="text-white px-2">
            <i class="px-1 fa fa-phone"></i>
            <span class="d-md-none">(216) 44251581</span>
          </a>
        </address>
        <a href="connexion.php" title="connexion" class="text-white">
          <i class="px-1 far fa-user"></i><span class="d-md-none">Connexion</span>
        </a>
      </div>
    </div>
    <div id="menu-bar">
      <div class="container py-3 px-2">
        <a class="current" href="index.php" title="accueil"><img src="../public/images/logo.jfif" alt="logo"></a>
        <ul>
          <li><a href="index.php" title="accueil" class="text-black">Accueil</a></li>
          <li><a href="announcements.php" title="annoces" class="px-2 text-black">Annonces</a></li>
          <li><a href="contact.php" title="contact" class="text-black">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>