<main>
  <section id="home">
    <div id="bloc-search-container" class="container">
      <div id="bloc-search">
        <div id="bloc-search-area">
          <div class="px-2">
            <p>Recherche par zone</p>
          </div>
          <div class="px-2">
            <div class="select-container">
              <label for="country">Pays</label>
              <select name="country" id="country">
                <option value="1">option 1</option>
                <option value="2">option 2</option>
                <option value="3">option 3</option>
                <option value="4">option 4</option>
                <option value="5">option 5</option>
              </select>
            </div>
            <div class="select-container">
              <label for="state">Etat</label>
              <select name="state" id="state">
                <option value="1">option 1</option>
                <option value="2">option 2</option>
                <option value="3">option 3</option>
                <option value="4">option 4</option>
                <option value="5">option 5</option>
              </select>
            </div>
            <div class="select-container">
              <label for="city">Ville</label>
              <select name="city" id="city">
                <option value="1">option 1</option>
                <option value="2">option 2</option>
                <option value="3">option 3</option>
                <option value="4">option 4</option>
                <option value="5">option 5</option>
              </select>
            </div>
          </div>
          <div class="px-2 py-2">
            <button class="btn-primary w-100">Rechercher</button>
          </div>
        </div>
        <div id="bloc-search-zip">
          <div class="px-2">
            <p>Recherche par Code postal</p>
          </div>
          <div class="px-2">
            <label for="zip">Code postal</label>
            <input name="zip" id="zip" type="text" placeholder="Ex: 3021">
          </div>
          <div class="px-2 py-2">
            <button class="btn-primary w-100">Rechercher</button>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="locations" class="container">
    <h2>Endroits populaires</h2>
    <div class="locations-container">
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
      <div class="locations-item py-2">
        <div>
          <img src="https://heymondo.com/blog/wp-content/uploads/2021/04/2.jpg" alt=""/>
          <p>Egypt</p>
        </div>
      </div>
    </div>
  </section>
  <section id="possibilities">
    <div class="container">
      <h2>Notre possibilités</h2>
      <ul class="mt-4">
        <li id="possibility1">
          <i class="fas fa-building"></i>
          <h4>Annoce des Appartements </h4>                    
          <p>Louer votre appartement, Annonces des chambres et appartements en location</p>
        </li>
        <li id="possibility2">
          <i class="fas fa-house-user"></i>
          <h4>Chercher un colocataire</h4>                    
          <p>Trouver des personnes pour partager. Vous pouvez trouver des informations sur les personnes qui recherchent des colocations </p>
        </li>
        <li id="possibility3">
          <i class="fas fa-hotel"></i>
          <h4>Chercher une collocation</h4>                    
          <p>Trouvez rapidement un logement à partager en colocation avec des colocataires. Votre future logement est ici </p>
        </li>
        <div class="clear"></div>  
      </ul>
    </div>
</section>
</main>