<main>
  <section id="home">
    <div id="bloc-search-container" class="container">
      <div id="bloc-search">
        <div id="bloc-search-area">
          <div class="px-2">
            <p>Recherche par zone</p>
          </div>
          <div class="px-2">
            <div class="select-container">
              <label for="country">Pays</label>
              <select name="country" id="country">
                <option value="1">option 1</option>
                <option value="2">option 2</option>
                <option value="3">option 3</option>
                <option value="4">option 4</option>
                <option value="5">option 5</option>
              </select>
            </div>
            <div class="select-container">
              <label for="state">Etat</label>
              <select name="state" id="state">
                <option value="1">option 1</option>
                <option value="2">option 2</option>
                <option value="3">option 3</option>
                <option value="4">option 4</option>
                <option value="5">option 5</option>
              </select>
            </div>
            <div class="select-container">
              <label for="city">Ville</label>
              <select name="city" id="city">
                <option value="1">option 1</option>
                <option value="2">option 2</option>
                <option value="3">option 3</option>
                <option value="4">option 4</option>
                <option value="5">option 5</option>
              </select>
            </div>
          </div>
        </div>
        <div id="bloc-search-zip">
          <div class="px-2">
            <p>Recherche par Code postal</p>
          </div>
          <div class="px-2">
            <label for="zip">Code postal</label>
            <input name="zip" id="zip" type="text" placeholder="Ex: 3021">
          </div>
        </div>
      </div>
    </div>
  </section>
</main>